### ISSUE TITLE
Extra input

### ISSUE THREAD

**Issue by obrok** [bitwalker/combine#13]
There doesn't seem to be a way to differentiate inputs where there was some extra characters at the end from inputs where the whole string was consumed.

``` elixir
iex(16)> Combine.parse("aaaaa", many(char("a")))
[["a", "a", "a", "a", "a"]]
iex(17)> Combine.parse("aaaaab", many(char("a")))
[["a", "a", "a", "a", "a"]]
```

Is this by design? If yes then maybe there should be another parsing function that rejects such strings.

**Comment by sasa1977** [comment]
Can't you use eof for this?

``` elixir
iex(1)> Combine.parse("aa", many(char("a")) |> eof())
[["a", "a"]]

iex(2)> Combine.parse("ab", many(char("a")) |> eof())
{:error, "Expected end of input at line 1, column 1"}
```

**Comment by obrok** [comment]
Right! Forgot about that :)
