### ISSUE TITLE
exposing defparser

### ISSUE THREAD

**Issue by sasa1977** [bitwalker/combine#14]
Currently, [defparser is not a part of the public api](https://github.com/bitwalker/combine/blob/master/lib/combine/helpers.ex#L2). However, we have encountered some situations where we needed to create additional parsers. Would you mind if this API was documented and officially supported?

Some of these parsers might be in fact useful for the `Combine` itself, but it's too early to tell. So I'd like to have an option to first create such parsers in our project (which resolves our immediate problems), and then once/if they prove useful, send a PR upstream.

**Comment by bitwalker** [comment]
I'm cool with exposing it. I think the main reason I didn't was because it felt awkward to work with, and so probably only useful to Combine, but with your recent PR which cleans it up a bit, I feel a lot better about it. With your example of a lazy parser definition, it also looks quite usable.

**Comment by sasa1977** [comment]
Great! I'll make a PR for that. We already have a couple of parsers which we needed for our case, so I'll probably send those as well in separate pulls.

**Comment by bitwalker** [comment]
Sounds awesome :). Thanks so much for contributing back!
