### ISSUE TITLE
Combine throws an error when processing unicode characters.

### ISSUE THREAD

**Issue by ghost** [bitwalker/combine#2]
I am using Combine to parse arbitrary user input, which involves sometimes to deal with unicode characters (for instance, quotes such as “ and ”).  
However, Combine doesn't seem to like them much…

```
17:37:20.242 [error] Process #PID<0.335.0> raised an exception
** (FunctionClauseError) no function clause matching in Combine.Parsers.Text.char_impl/2
    lib/combine/parsers/text.ex:67: Combine.Parsers.Text.char_impl(%Combine.ParserState{column: 43, error: nil, input: <<128, 156, 73, 39, 109, 32, 103, 111, 105, 110, 103, 32, 116, 111, 32, 107
, 105, 108, 108, 32, 121, 111, 117, 33, 226, 128, 157, 34>>, line: 1, results: [], status: :ok}, 34)
    lib/combine/parsers/base.ex:172: Combine.Parsers.Base.do_pipe/3
    lib/combine/parsers/base.ex:161: Combine.Parsers.Base.pipe_impl/3
    lib/combine/parsers/base.ex:172: Combine.Parsers.Base.do_pipe/3
    lib/combine/parsers/base.ex:161: Combine.Parsers.Base.pipe_impl/3
    lib/combine/parsers/base.ex:69: Combine.Parsers.Base.map_impl/3
    lib/combine/parsers/base.ex:172: Combine.Parsers.Base.do_pipe/3
    lib/combine/parsers/base.ex:161: Combine.Parsers.Base.pipe_impl/3
```

**Comment by bitwalker** [comment]
@Annwenn Do you have a copy of the user input that caused this failure? The error message has the raw binary at the point of failure, but having the entire string up to that point would be helpful in troubleshooting why it failed. The char parser is currently assuming that input is UTF-8 encoded (if you look at the parser implementation, it is pulling of characters one by one using pattern matching with the `utf8` pattern.

**Comment by bitwalker** [comment]
It might also be helpful to have the parser you are using, just in case it's being caused by a specific combination of parsers.

**Comment by ghost** [comment]
My parser is the following:

```
    parser = sep_by1(map(
    sequence([
      pair_left(word, char(?=)),
        between(char(?"), word_of(~r/[\w\s]/), char(?"))
      ]),
        fn [key, value] -> {key, value} end),
        string("::"))
```

**Comment by bitwalker** [comment]
@Annwenn This ended up being due to how `word_of` was working. It matched somehow on half of the grapheme for the unicode quotation mark, which then broke any further utf-8 parsing. I've made a modification which allows you to pass along flags with your regular expression, so that you can enable unicode mode for the pattern being provided. If you change your parser to use `word_of(~r/[\w\s]/u)`, it will returns the same result as if you swapped those unicode quotes with regular single quotes. Which is to say, the second key/value pair will not be parsed successfully because of the embedded quotes, but an error is no longer thrown.

**Comment by ghost** [comment]
Hmm… Then how do you think I might adapt the parser to accept quotes? Would they just have to be escaped with `\`?

**Comment by bitwalker** [comment]
I would use `between(char(?"), many(none_of(char, ["\""])), char(?"))`. This will parse zero or more characters which aren't a double quote contained between two quotes. The `many/none_of` combination will return a list of characters (as strings) which you can then join with `Enum.join` if desired.

**Comment by ghost** [comment]
okay, thanks a lot :)
