### ISSUE TITLE
relax typespec?

### ISSUE THREAD

**Issue by sasa1977** [bitwalker/combine#27]
Recently, in commit 27b02535f96af11b4a54124db9025c31a09631db, typspecs have been added. One of them specifies that the input in `%ParserState{}` is always supposed to be a string.  It is true that some parsers (e.g. `Parsers.String` and `Parsers.Binary`) require string input. However, I think most/all in `Parsers.Base` don't care about the input type. Moreover, in our project, we're actually using non-string inputs (list of custom tokens), and easily process them with our custom parsers + the ones from `Parsers.Base`. Unfortunately, due to current typespec in Combine, we get a lot of dialyzer errors.

So I'd like to propose relaxing typespec for the input. One option is to allow `binary | [any]`, another is to just use `any`. For our case, I think the former option will suffice. If you're fine with this, I'll be happy to prepare a PR.

**Comment by bitwalker** [comment]
Hey @sasa1977 sorry for missing this issue, I'd be open to relaxing the typespec if you want to submit a PR for it!
