### ISSUE TITLE
Option to get `Keyword` with label as keys like [year: 2017, day: 16]?

### ISSUE THREAD

**Issue by msoedov** [bitwalker/combine#32]
I think it might be more convenient to play around `Keyword` rather than `List`

**Comment by bitwalker** [comment]
Could you give an example of where/how you are wanting to use this?

**Comment by msoedov** [comment]
My bad, let me give you my example, suppose we have a date parser like

```elixir
  defp date do
    label(word, "month")
    |> ignore(char(" "))
    |> label(integer, "day")
    |> ignore(char(" "))
    |> label(integer, "hour")
    |> ignore(char(":"))
    |> label(integer, "minute")
    |> ignore(char(":"))
    |> label(integer, "seconds")
    |> ignore(char(" "))
  end
```

And as an output we currently get List of parsed values in order of applied parsers

```elixir
MyParserModule.parse("Apr 10 02:49:33")
...> ["Apr", 10, 2, 49, 33]
```
What can be really helpful for further processing is to get from parser a keyword list

```elixir 
[month: "Apr", day:  10, hour: 2,  minute: 49, seconds: 33]
```
To achieve this we can use `Enum.zip`

```elixir
Enum.zip([:month, :day, :hour, :minute, :seconds],  ["Apr", 10, 2, 49, 33])
..> [month: "Apr", day: 10, hour: 2, minute: 49, seconds: 33]
```

However it's become harder to manage when you have combination of several parsers with labels.


```elixir
  defp parser do
      date |> host_name |> meta
  end

  defp date do
    label(word, "month")
    |> ignore(char(" "))
    |> label(integer, "day")
    |> ignore(char(" "))
    |> label(integer, "hour")
    |> ignore(char(":"))
    |> label(integer, "minute")
    |> ignore(char(":"))
    |> label(integer, "seconds")
  end

  defp host_name(p) do
    p
    |> label(word, "hostname")
  end

  defp meta(p) do
    p
    |> label(word, "key")
    |> ignore(char("="))
    |> label(word, "val")
  end

```

WDYT?

**Comment by bitwalker** [comment]
I'll have to take a closer look, but it should be possible to extend the functionality of the `label` combinator to wrap parsed values in a key/value tuple, where the label is the key, and convert the label to an atom so that the `Keyword` module can be used.

**Comment by msoedov** [comment]
@bitwalker 
I am working on PR, basically I have added list of label names to `%ParserState{}`
```elixir
  @spec label(previous_parser, parser, String.t) :: parser
  defparser label(%ParserState{status: :ok} = state, parser, name) when is_function(parser, 1) do
    case parser.(state) do
      %ParserState{status: :ok, labels: labels} = s -> %{s | labels: [name | labels]}
      %ParserState{line: line, column: col} = s ->
        %{s | :error => "Expected `#{name}` at line #{line}, column #{col + 1}."}
    end
  end
```

I'm still experimenting with the library api, there are a couple corner cases still need to be fixed. But basic examples are working  

```elixir
assert [year: 2014, month: 7, day: 22] = Combine.parse(@datetime, DateTimeParser.date(), kw: true)
assert [hour: 12, minute: 30, seconds: 5.0002] = Combine.parse("12:30:05.0002Z", DateTimeParser.time(), kw: true)
```

**Comment by yonkeltron** [comment]
Hugely supportive of this feature. It would improve my life and usage of this library significantly.

**Comment by bitwalker** [comment]
This has been merged in master, will be pushing a new release today.
