### ISSUE TITLE
take while misbehaving (for me)

### ISSUE THREAD

**Issue by jxxcarlson** [bitwalker/combine#36]
I am not getting the expected behavior with `take_while` -- but perhaps it is just me:-)

When I do the following, according to the examples in the docs, I get what is expected:
```
iex(3)> parser = take_while(fn ?a -> true; _ -> false end)
#Function<34.105957604/1 in Combine.Parsers.Text.take_while/2>
iex(4)> Combine.parse("aaaaabbbbb", parser)
['aaaaa']
```
Now I want to accept strings that do not have characters in a specific list:
```
iex(5)> parser2 = take_while(fn a -> !Enum.member?(['-', '='], a) end)
#Function<34.105957604/1 in Combine.Parsers.Text.take_while/2>
iex(6)> Combine.parse("aaaaabbbbb", parser2)                          
['aaaaabbbbb']
iex(7)> Combine.parse("aaaaa-bbbbb", parser2)
['aaaaa-bbbbb']
```

The first string above should be accepted, but in the second
case, one should get just `['aaaaa']`

I tried a few more tests to see what I was missing:

```
iex(8)> foo = fn a -> !Enum.member?(['-', '='], a) end
#Function<6.52032458/1 in :erl_eval.expr/5>
iex(9)> foo.('G')
true
iex(10)> foo.('-')
false
iex(11)> parser3 = take_while(foo)
#Function<34.105957604/1 in Combine.Parsers.Text.take_while/2>
iex(12)> Combine.parse("aaaaa-bbbbb", parser3)         
['aaaaa-bbbbb']
iex(13)> Combine.parse("aaaaabbbbb", parser3) 
['aaaaabbbbb']
```

**Comment by NobbZ** [comment]
The predicate will receive chars, not char lists. So enum. Member? ('-=',
a) will probably work.

James Carlson <notifications@github.com> schrieb am So., 16. Apr. 2017,
13:35:

**Comment by bitwalker** [comment]
@jxxcarlson Yes, what @NobbZ mentioned is correct, the predicate is dealing with chars, e.g. `[?-, ?=]` rather than charlists `['-', '=']`, which is why all characters are returned

**Comment by jxxcarlson** [comment]
Thank you both very much!  (I am a noob at both Elixir and Combinators).  With this cleared up, I'm making good progress using Combine.
